In [1]:
#
# * File:    Twitter_Persona_GloVe.py
# *
# * Author1:  Pavan Kumar K N (pavankumar.karkekopp@ucalgary.ca)
# * Date:     11th Aug 2019
# * Summary of File:
# * Explore mbti_1.csv file acquired from https://www.kaggle.com/datasnaek/mbti-type
# * Apply state-of-the-art reported publicly
# * Build classifier model that is better using machine learning techniques

#Just making sure the right environment is running this script
import sys
sys.executable

'C:\\ProgramData\\Anaconda3\\python.exe'

In [8]:
#Read Data
import numpy as np
import pandas as pd
import sklearn
import re
import pickle

from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords 
from nltk import word_tokenize

from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.manifold import TSNE

from numpy import loadtxt
from xgboost import XGBClassifier
import xgboost as xgb
from sklearn import svm
from sklearn import metrics
from sklearn.model_selection import train_test_split, GridSearchCV, cross_validate
from imblearn.over_sampling import SMOTE

from sklearn.decomposition import PCA
import pylab as pl
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
from __future__ import print_function

import os
import sys
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.layers import Dense, Input, Flatten, Dropout
from keras.layers import Conv1D, MaxPooling1D, Embedding, LSTM
from keras.models import Model

mbti_1 = pd.read_csv('data/mbti_1.csv') 
posts = mbti_1.posts
labels = mbti_1.type

BASE_DIR = ''
GLOVE_DIR = "data/glove.twitter.27B"
MAX_SEQUENCE_LENGTH = 600
MAX_NB_WORDS = 2000
EMBEDDING_DIM = 100
VALIDATION_SPLIT = 0.2


In [3]:
#Read the dataset
mbti_data = pd.read_csv("data/mbti_1.csv")

In [4]:
#Print first 5 entries in the dataset
mbti_data.head()

type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [5]:
raw_posts = mbti_data.posts.values

In [6]:
#Split posts by the delimiter, which is ||| as we can see in row 0 and 4 above
filtered_posts = [p.split("|||") for p in raw_posts]

In [7]:
#Example of two tweets from row 0
for i in range(5):
    print("Tweet #{}:   {}".format(i+1,filtered_posts[0][i]))

Tweet #1:   'http://www.youtube.com/watch?v=qsXHcwe3krw
Tweet #2:   http://41.media.tumblr.com/tumblr_lfouy03PMA1qa1rooo1_500.jpg
Tweet #3:   enfp and intj moments  https://www.youtube.com/watch?v=iz7lE1g4XM4  sportscenter not top ten plays  https://www.youtube.com/watch?v=uCdfze1etec  pranks
Tweet #4:   What has been the most life-changing experience in your life?
Tweet #5:   http://www.youtube.com/watch?v=vXZeYwwRDw8   http://www.youtube.com/watch?v=u8ejam5DP3E  On repeat for most of today.


In [13]:
def encode_types(row):
    t=row['type']

    I = 0
    N = 0
    T = 0
    J = 0
    
    if t[0] == 'I': I = 1
    elif t[0] == 'E': I = 0
    else: print('Could not identify label for I-E')
        
    if t[1] == 'N': N = 1
    elif t[1] == 'S': N = 0
    else: print('Could not identify label for N-S')
        
    if t[2] == 'T': T = 1
    elif t[2] == 'F': T = 0
    else: print('Could not identify label for T-F')
        
    if t[3] == 'J': J = 1
    elif t[3] == 'P': J = 0
    else: print('Could not identify label for J-P')
    return pd.Series( {'IE':I, 'NS':N , 'TF': T, 'JP': J }) 

In [14]:
mbti_data_encoded = mbti_data.join(mbti_data.apply(lambda row: encode_types(row), axis=1))

In [15]:
mbti_data_encoded.head()

type                                              posts  IE  NS  TF  JP
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...   1   1   0   1
1  ENTP  'I'm finding the lack of me in these posts ver...   0   1   1   0
2  INTP  'Good one  _____   https://www.youtube.com/wat...   1   1   1   0
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...   1   1   1   1
4  ENTJ  'You're fired.|||That's another silly misconce...   0   1   1   1

In [16]:
#Function to binarize the types into simple lists instead of pandas.series
personality_binary = {'I':1, 'E':0, 'N':1,'S':0, 'T':1, 'F':0, 'J':1, 'P': 0}
binary_personality = [{1:'I', 0:'E'}, 
                      {1:'N', 0:'S'},
                      {1:'T', 0:'F'},
                      {1:'J', 0:'P'}]

def translate_personality(personality):
    # transform mbti to binary vector
    return [personality_binary[l] for l in personality]


def translate_binary(personality):
    # transform binary vector to mbti personality
    s = ""
    for i, l in enumerate(personality):
        s += binary_personality[i][l]
    return s



In [17]:
d = mbti_data_encoded.head(4)
list_personality_bin = np.array([translate_personality(p) for p in mbti_data_encoded.type])
print("Binarize MBTI list: \n%s" % list_personality_bin)

Binarize MBTI list: 
[[1 1 0 1]
 [0 1 1 0]
 [1 1 1 0]
 ...
 [1 1 1 0]
 [1 1 0 0]
 [1 1 0 0]]


### Data Preprocessing
* Remove urls
* Keep only words and make it lowercase
* Lemmatize each word
* Remove MBTI profiles strings. Too many appear in the posts!

In [27]:
mbti_data_encoded

type                                              posts  IE  NS  TF  JP
0     INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...   1   1   0   1
1     ENTP  'I'm finding the lack of me in these posts ver...   0   1   1   0
2     INTP  'Good one  _____   https://www.youtube.com/wat...   1   1   1   0
3     INTJ  'Dear INTP,   I enjoyed our conversation the o...   1   1   1   1
4     ENTJ  'You're fired.|||That's another silly misconce...   0   1   1   1
5     INTJ  '18/37 @.@|||Science  is not perfect. No scien...   1   1   1   1
6     INFJ  'No, I can't draw on my own nails (haha). Thos...   1   1   0   1
7     INTJ  'I tend to build up a collection of things on ...   1   1   1   1
8     INFJ  I'm not sure, that's a good question. The dist...   1   1   0   1
9     INTP  'https://www.youtube.com/watch?v=w8-egj0y8Qs||...   1   1   1   0
10    INFJ  'One time my parents were fighting over my dad...   1   1   0   1
11    ENFJ  'https://www.youtube.com/watch?v=PLAaiKvHvZs||...   0   1   0   1
12    INFJ  'Joe santagato - ENTP|||ENFJ or  ENTP?   I'm n...   1   1   0   1
13    INTJ  'Fair enough, if that's how you want to look a...   1   1   1   1
14    INTP  'Basically this...  https://youtu.be/1pH5c1Jkh...   1   1   1   0
15    INTP  'Your comment screams INTJ, bro. Especially th...   1   1   1   0
16    INFJ  'some of these both excite and calm me:  BUTTS...   1   1   0   1
17    INFP  'I think we do agree. I personally don't consi...   1   1   0   0
18    INFJ  'I fully believe in the power of being a prote...   1   1   0   1
19    INFP  'That's normal, it happens also to me. If I am...   1   1   0   0
20    INTP  'Steve Job's was recognized for his striving f...   1   1   1   0
21    INFJ  'It is very annoying to be misinterpreted. Esp...   1   1   0   1
22    ENTJ  'Now I'm interested. But too lazy to go resear...   0   1   1   1
23    INFP  '45016 urh sorry uh. couldn't resist.|||all of...   1   1   0   0
24    ENTJ  'Still going strong at just over the two year ...   0   1   1   1
25    INFP  'Personally, I was thinking this would be more...   1   1   0   0
26    ENFP  'He doesn't want to go on the trip without me,...   0   1   0   0
27    ISFP  'They paint without numbers|||I'd guess at ist...   1   0   0   0
28    INFP  'Basically, my main questions are : What do yo...   1   1   0   0
29    INFJ  'I think that that can absolutely be true of i...   1   1   0   1
...    ...                                                ...  ..  ..  ..  ..
8645  INFJ  'I play cello, and I'm also a classically trai...   1   1   0   1
8646  INFP  Its more or less based on how YOU experienced ...   1   1   0   0
8647  INTP  Socionics picked up on this.  They call it vis...   1   1   1   0
8648  INFP  'Good advice, thank you.|||I am in a tough sit...   1   1   0   0
8649  INFP  https://www.youtube.com/watch?v=nPDusM-75FE  e...   1   1   0   0
8650  INFJ  'I think the real question is whether INFJs ca...   1   1   0   1
8651  ISTP  '-Being alone -Being insensitive  -Over thinki...   1   0   1   0
8652  ISFJ  'Being assertive and standing up for myself is...   1   0   0   1
8653  INFP  'You should do whatever it is you want. If you...   1   1   0   0
8654  ISTJ  'Assuming I had a hand in it, I always at leas...   1   0   1   1
8655  INFJ  'I find that poster and your facial expression...   1   1   0   1
8656  INFJ  Rim  In some approximate order, it seems like ...   1   1   0   1
8657  INTJ  Social  1) Generally, I positively associate w...   1   1   1   1
8658  ESFJ  'Don't worry, I do that too when a car comes c...   0   0   0   1
8659  ENFP  'leoni I had really bad social anxiety until I...   0   1   0   0
8660  INFP  'I love the vastness of the sky, because my pr...   1   1   0   0
8661  ENTP  '**haven't logged in and read posts for over 6...   0   1   1   0
8662  INTJ  'I can't say I have any one specific belief. I...   1   1   1   1
8663  INTP  'doesn't matter, you don't have a choice, Elec...   1   1   1   0
8664  INTP  'https://www.you

In [72]:
#List of strings to remove from the corpus
unique_type_list = ['INFJ', 
                    'ENTP', 
                    'INTP', 
                    'INTJ', 
                    'ENTJ', 
                    'ENFJ', 
                    'INFP', 
                    'ENFP',
                    'ISFP', 
                    'ISTP', 
                    'ISFJ', 
                    'ISTJ', 
                    'ESTP', 
                    'ESFP', 
                    'ESTJ', 
                    'ESFJ']

unique_type_list = [x.lower() for x in unique_type_list]

# Initialize for Lemmatization
stemmer = PorterStemmer()
lemmatiser = WordNetLemmatizer()

def pre_process_data(data, remove_stop_words = True, remove_mbti_profiles = True):
    list_personality = []
    list_posts = []
    len_data = len(data)
    i=0
    
    for row in data.iterrows():
        i+=1
        if (i % 500 == 0 or i == 1 or i == len_data):
            print("%s of %s rows" % (i, len_data))

        ##### Remove and clean comments
        posts = row[1].posts
        filtered_post = re.sub("http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|(?:%[0-9a-fA-F][0-9a-fA-F]))+", " ", posts)
        filtered_post_list = filtered_post.split("|||")
        i=0
        for pos in filtered_post_list:
            print("Tweet #{}:   {}".format(i+1, pos))
            i += 1
            pos = re.sub("[^a-zA-Z]", " ", pos)
            pos = re.sub(" +", " ", pos).lower()
            if remove_stop_words:
                pos = " ".join([lemmatiser.lemmatize(w) for w in pos.split(' ') if w not in stopwords.words("english")])
            else:
                pos = " ".join([lemmatiser.lemmatize(w) for w in pos.split(' ')])

            if remove_mbti_profiles:
                for t in unique_type_list:
                    pos = pos.replace(t, "")

        type_labelized = translate_personality(row[1].type)
        list_personality.append(type_labelized)
        list_posts.append(filtered_post_list)
        break

    list_posts = np.array(list_posts)
    list_personality = np.array(list_personality)
    return list_posts, list_personality


In [73]:
list_posts, list_personality  = pre_process_data(mbti_data_encoded, remove_stop_words=False)

1 of 8675 rows
Tweet #1:   ' 
Tweet #2:    
Tweet #3:   enfp and intj moments     sportscenter not top ten plays     pranks
Tweet #4:   What has been the most life-changing experience in your life?
Tweet #5:          On repeat for most of today.
Tweet #6:   May the PerC Experience immerse you.
Tweet #7:   The last thing my INFJ friend posted on his facebook before committing suicide the next day. Rest in peace~    
Tweet #8:   Hello ENFJ7. Sorry to hear of your distress. It's only natural for a relationship to not be perfection all the time in every moment of existence. Try to figure the hard times as times of growth, as...
Tweet #9:   84389  84390       ...
Tweet #10:   Welcome and stuff.
Tweet #11:      Game. Set. Match.
Tweet #12:   Prozac, wellbrutin, at least thirty minutes of moving your legs (and I don't mean moving them while sitting in your same desk chair), weed in moderation (maybe try edibles as a healthier alternative...
Tweet #13:   Basically come up with three items you'

In [71]:
list_posts[0], list_personality[0]

(array(["' ", ' ',
        'enfp and intj moments     sportscenter not top ten plays     pranks',
        'What has been the most life-changing experience in your life?',
        '       On repeat for most of today.',
        'May the PerC Experience immerse you.',
        'The last thing my INFJ friend posted on his facebook before committing suicide the next day. Rest in peace~    ',
        "Hello ENFJ7. Sorry to hear of your distress. It's only natural for a relationship to not be perfection all the time in every moment of existence. Try to figure the hard times as times of growth, as...",
        '84389  84390       ...', 'Welcome and stuff.',
        '   Game. Set. Match.',
        "Prozac, wellbrutin, at least thirty minutes of moving your legs (and I don't mean moving them while sitting in your same desk chair), weed in moderation (maybe try edibles as a healthier alternative...",
        "Basically come up with three items you've determined that each type (or whichever types y

#### Embedding Matrix with GloVe

In [10]:
# build index mapping words in the embeddings set to their embedding vector

print('Indexing word vectors.')

embeddings_index = {}
f = open(os.path.join(GLOVE_DIR, 'glove.twitter.27B.100d.txt'), encoding="utf=8")
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

Indexing word vectors.
Found 1193514 word vectors.


In [22]:
list_posts[0], list_personality[0]

(['',
  '',
  'and',
  '',
  'moment',
  'sportscenter',
  'not',
  'top',
  'ten',
  'play',
  'prank',
  'what',
  'ha',
  'been',
  'the',
  'most',
  'life',
  'changing',
  'experience',
  'in',
  'your',
  'life',
  'on',
  'repeat',
  'for',
  'most',
  'of',
  'today',
  'may',
  'the',
  'perc',
  'experience',
  'immerse',
  'you',
  'the',
  'last',
  'thing',
  'my',
  '',
  'friend',
  'posted',
  'on',
  'his',
  'facebook',
  'before',
  'committing',
  'suicide',
  'the',
  'next',
  'day',
  'rest',
  'in',
  'peace',
  'hello',
  '',
  'sorry',
  'to',
  'hear',
  'of',
  'your',
  'distress',
  'it',
  's',
  'only',
  'natural',
  'for',
  'a',
  'relationship',
  'to',
  'not',
  'be',
  'perfection',
  'all',
  'the',
  'time',
  'in',
  'every',
  'moment',
  'of',
  'existence',
  'try',
  'to',
  'figure',
  'the',
  'hard',
  'time',
  'a',
  'time',
  'of',
  'growth',
  'a',
  'welcome',
  'and',
  'stuff',
  'game',
  'set',
  'match',
  'prozac',
  'wellbr